language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install pep8
before_script:
  - pep8 --ignore=E121,E123,E126,E226,E24,E704,E501,E731 .
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test
